[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["cd server && npm run build", "cd server && npx prisma generate"]

[start]
cmd = "cd server && npm start"

